[2023-10-22T06:33:56.801+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dagg.task1 manual__2023-10-22T06:33:56.041659+00:00 [queued]>
[2023-10-22T06:33:56.812+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dagg.task1 manual__2023-10-22T06:33:56.041659+00:00 [queued]>
[2023-10-22T06:33:56.812+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-22T06:33:56.826+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): task1> on 2023-10-22 06:33:56.041659+00:00
[2023-10-22T06:33:56.831+0000] {standard_task_runner.py:57} INFO - Started process 198 to run task
[2023-10-22T06:33:56.834+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dagg', 'task1', 'manual__2023-10-22T06:33:56.041659+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/first_dags.py', '--cfg-path', '/tmp/tmpbkcayvp3']
[2023-10-22T06:33:56.836+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask task1
[2023-10-22T06:33:56.873+0000] {task_command.py:416} INFO - Running <TaskInstance: first_dagg.task1 manual__2023-10-22T06:33:56.041659+00:00 [running]> on host dd1abe773e49
[2023-10-22T06:33:56.938+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='first_dagg' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T06:33:56.041659+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T06:33:56.041659+00:00'
[2023-10-22T06:33:56.939+0000] {ssh.py:135} INFO - Creating ssh_client
[2023-10-22T06:33:57.082+0000] {ssh.py:112} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2023-10-22T06:33:57.099+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 172, in execute
    with self.get_ssh_client() as ssh_client:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 136, in get_ssh_client
    return self.get_hook().get_conn()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 113, in get_hook
    self.ssh_hook = SSHHook(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/hooks/ssh.py", line 151, in __init__
    conn = self.get_connection(self.ssh_conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 477, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `host_machine` isn't defined
[2023-10-22T06:33:57.105+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=first_dagg, task_id=task1, execution_date=20231022T063356, start_date=20231022T063356, end_date=20231022T063357
[2023-10-22T06:33:57.123+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task task1 (The conn_id `host_machine` isn't defined; 198)
[2023-10-22T06:33:57.167+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T06:33:57.189+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
