[2023-10-22T05:32:32.376+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dagg.task1 manual__2023-10-22T05:32:31.826332+00:00 [queued]>
[2023-10-22T05:32:32.387+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dagg.task1 manual__2023-10-22T05:32:31.826332+00:00 [queued]>
[2023-10-22T05:32:32.388+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-22T05:32:32.408+0000] {taskinstance.py:1382} INFO - Executing <Task(SSHOperator): task1> on 2023-10-22 05:32:31.826332+00:00
[2023-10-22T05:32:32.414+0000] {standard_task_runner.py:57} INFO - Started process 834 to run task
[2023-10-22T05:32:32.417+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dagg', 'task1', 'manual__2023-10-22T05:32:31.826332+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/first_dags.py', '--cfg-path', '/tmp/tmpcdql4co5']
[2023-10-22T05:32:32.419+0000] {standard_task_runner.py:85} INFO - Job 55: Subtask task1
[2023-10-22T05:32:32.468+0000] {task_command.py:416} INFO - Running <TaskInstance: first_dagg.task1 manual__2023-10-22T05:32:31.826332+00:00 [running]> on host 0a51e56afb27
[2023-10-22T05:32:32.579+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='first_dagg' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T05:32:31.826332+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T05:32:31.826332+00:00'
[2023-10-22T05:32:32.579+0000] {ssh.py:135} INFO - Creating ssh_client
[2023-10-22T05:32:32.623+0000] {ssh.py:112} INFO - ssh_hook is not provided or invalid. Trying ssh_conn_id to create SSHHook.
[2023-10-22T05:32:32.632+0000] {base.py:73} INFO - Using connection ID 'host_machine' for task execution.
[2023-10-22T05:32:32.634+0000] {ssh.py:300} WARNING - No Host Key Verification. This won't protect against Man-In-The-Middle attacks
[2023-10-22T05:32:32.650+0000] {transport.py:1893} INFO - Connected (version 2.0, client OpenSSH_8.9p1)
[2023-10-22T05:32:32.825+0000] {transport.py:1893} INFO - Authentication (password) successful!
[2023-10-22T05:32:32.826+0000] {ssh.py:476} INFO - Running command: cd /home/***/data_science/web_scrap/rumah/rumah && shiny --help 
[2023-10-22T05:32:32.901+0000] {ssh.py:527} WARNING - bash: line 1: shiny: command not found
[2023-10-22T05:32:32.924+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 173, in execute
    result = self.run_ssh_client_command(ssh_client, self.command, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 161, in run_ssh_client_command
    self.raise_for_status(exit_status, agg_stderr, context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/ssh/operators/ssh.py", line 154, in raise_for_status
    raise AirflowException(f"SSH operator error: exit status = {exit_status}")
airflow.exceptions.AirflowException: SSH operator error: exit status = 127
[2023-10-22T05:32:32.928+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=first_dagg, task_id=task1, execution_date=20231022T053231, start_date=20231022T053232, end_date=20231022T053232
[2023-10-22T05:32:32.944+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 55 for task task1 (SSH operator error: exit status = 127; 834)
[2023-10-22T05:32:32.991+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T05:32:33.043+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
