[2023-10-22T01:30:53.603+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: first_dagg.scrape_data manual__2023-10-22T01:30:52.623661+00:00 [queued]>
[2023-10-22T01:30:53.610+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: first_dagg.scrape_data manual__2023-10-22T01:30:52.623661+00:00 [queued]>
[2023-10-22T01:30:53.610+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-10-22T01:30:53.624+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): scrape_data> on 2023-10-22 01:30:52.623661+00:00
[2023-10-22T01:30:53.628+0000] {standard_task_runner.py:57} INFO - Started process 211 to run task
[2023-10-22T01:30:53.629+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'first_dagg', 'scrape_data', 'manual__2023-10-22T01:30:52.623661+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/first_dags.py', '--cfg-path', '/tmp/tmp7y84azzr']
[2023-10-22T01:30:53.631+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask scrape_data
[2023-10-22T01:30:53.671+0000] {task_command.py:416} INFO - Running <TaskInstance: first_dagg.scrape_data manual__2023-10-22T01:30:52.623661+00:00 [running]> on host 85da07900c55
[2023-10-22T01:30:53.758+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='me' AIRFLOW_CTX_DAG_ID='first_dagg' AIRFLOW_CTX_TASK_ID='scrape_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T01:30:52.623661+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T01:30:52.623661+00:00'
[2023-10-22T01:30:53.759+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-10-22T01:30:53.759+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', './script2.sh > mypipe1 ']
[2023-10-22T01:30:53.767+0000] {subprocess.py:86} INFO - Output:
[2023-10-22T01:30:53.771+0000] {subprocess.py:93} INFO - ./script2.sh: line 119: scrapy: command not found
[2023-10-22T01:30:53.771+0000] {subprocess.py:93} INFO - ./script2.sh: line 119: scrapy: command not found
[2023-10-22T01:30:53.772+0000] {subprocess.py:93} INFO - ./script2.sh: line 119: scrapy: command not found
[2023-10-22T01:30:53.772+0000] {subprocess.py:93} INFO - ./script2.sh: line 119: scrapy: command not found
[2023-10-22T01:30:53.772+0000] {subprocess.py:93} INFO - ./script2.sh: line 119: scrapy: command not found
[2023-10-22T01:30:53.773+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-10-22T01:30:53.783+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-10-22T01:30:53.787+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=first_dagg, task_id=scrape_data, execution_date=20231022T013052, start_date=20231022T013053, end_date=20231022T013053
[2023-10-22T01:30:53.802+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task scrape_data (Bash command failed. The command returned a non-zero exit code 127.; 211)
[2023-10-22T01:30:53.843+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T01:30:53.862+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
